In [3]:
!pip install pandas

Collecting pandas
  Downloading pandas-1.5.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 747.3 kB/s eta 0:00:0000:0100:01
Requirement already satisfied: python-dateutil>=2.8.1 in /home/koumon/miniconda3/envs/py38/lib/python3.8/site-packages (from pandas) (2.8.2)
Collecting numpy>=1.20.3
  Downloading numpy-1.23.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 870.6 kB/s eta 0:00:0000:0100:01
Requirement already satisfied: pytz>=2020.1 in /home/koumon/miniconda3/envs/py38/lib/python3.8/site-packages (from pandas) (2022.5)
Requirement already satisfied: six>=1.5 in /home/koumon/miniconda3/envs/py38/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: numpy, pandas
Successfully installed numpy-1.23.4 pandas-1.5.1

各種ライブラリをインポートする
ライブラリが無いエラーが出る場合は!pip install numpyのようにしてインストールする

In [4]:
import pandas as pd

In [ ]:
ペンギンデータセットをロードする  
- 3種類のペンギンのデータが合計344サンプル
- ペンギンの種類はアデリーペンギン（Adelie Penguin）、ジェンツーペンギン（Gentoo Penguin）
- 特徴量はsepal length,sepal width,petal length,petal width の4種類
- 種類は目的変数（target）に数値で格納されている（setosa:0,versicolor:1, virginica:2）

In [5]:
url = [
  # Adelie penguin data
  'https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-pal.219.3&entityid=002f3893385f710df69eeebe893144ff',
  # Gentoo penguin data
  'https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-pal.220.3&entityid=e03b43c924f226486f2f0ab6709d2381',
  # Chinstrap penguin data
  'https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-pal.221.2&entityid=fe853aa8f7a59aa84cdd3197619ef462',
]

df = pd.concat([
  pd.read_csv(url[0]),
  pd.read_csv(url[1]),
  pd.read_csv(url[2])
])

In [6]:
df.head()

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,2007-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN